### ISSUE TITLE
How to build my own dataset

### ISSUE THREAD

**Issue by virtualRooom** [mrakotosaon/diff-surface-triangulation#1]
Hi @mrakotosaon , thank you for sharing the code. I want to test the algorithm on my datasets,  what should I do.

**Comment by mrakotosaon** [comment]
Hi @virtualRooom ,

Thank you for your message. I will upload the code for preprocessing new datasets as soon as I can (normally before the end of the week) and keep you updated if it is not too urgent.
Thank you for your patience.
