### ISSUE TITLE
Mesh Rendering

### ISSUE THREAD

**Issue by dingirsu** [mrakotosaon/diff-surface-triangulation#2]
Thanks for your sharing code! I wonder what kind of mesh renderer used in your paper like Fig.5? I want to visualize my own triangle size error.

**Comment by mrakotosaon** [comment]
Hi @dingirsu 
We used blender to make the figures in the paper (including figure 5). For visualizing when working on the code and project we also used [polyscope](https://polyscope.run/py/) which is easier to set up.
