### ISSUE TITLE
What am I supposed to see in the output?

### ISSUE THREAD

**Issue by lukkio88** [mrakotosaon/diff-surface-triangulation#4]
Hi,

I came across your paper at Siggraph Asia 2021. It was interesting work so I wanted to try.
I managed to run everything and specifically I am running right now the `optimize_curvature` and it's running on a cat kind of mesh.

I am not sure what the final output of this process is supposed to be.
Also, can I change the input with any triangulated, manifold, mesh?

Thank you

**Comment by mrakotosaon** [comment]
Hi @lukkio88 ,

Optimize_curvature normally produces optimized patches in "data/curvature" if you keep the default paths. 
You can cut the boundaries of each patch in postprocessing if you need to combine the patches as we describe in Section 3.2 of the paper.

To input your own mesh, you should input a patch decomposition of your mesh with a corresponding parametrization that does not present overlappings. One possibility is to use the code in "preprocessing" and making sure that there are no overlapping.

**Comment by lukkio88** [comment]
Hi @mrakotosaon 
I can see the patches but the triangulations of these patches looks not much different from the input.
I was expecting a different triangulation maybe. I might also have missunderstood what the code dose in the first place.

My understanding, from the paper and you presentation, is that we would have a soft representation of the triangulation. Under the hood I would assume the code makes use of such soft representation to produce an actual triangulation.

Is this understanding correct?

Another question I have is how I can speedup the training a bit. I have a GTX 1070 (a bit old by now).
But I run out of memory as soon as I try to run the code on GPU.

I've also tried CPU, but it takes a lot of time (I think it took me half a day / a day for the mentioned test case).

**Comment by mrakotosaon** [comment]
Hi @lukkio88 
Yes we do use a representation of the triangulation that is soft during the optimization. However, the output that we save is a traditional discrete triangulation. In the curvature experiment, we align the triangle edges to directions with high curvature.
You  should normally get similar results to what we get in Figure 5 of our paper. Is this the case? Maybe the triangle size experiment would be easier to visualize?

Yes with the default paremeters you would need a GPU with higher memory, we report some numbers in table 3 and 4. However, you could use a smaller GPU if you separate the mesh into smaller patches

**Comment by mrakotosaon** [comment]
Hi @lukkio88 
It is a little bit difficult to see but in the second image it seems like consecutive edges are more aligned as they follow the curvature vector field. You can see almost straight lines formed of edges. Without the error coloring of the image, the triangle size experiment would definitely  be easier to interpret.
To split the mesh we used spectral clustering. The method is described in the paper  (section 3.2) and there is corresponding code in the 'preprocessing' directory
