### ISSUE TITLE
 https://github.com/mrakotosaon/diff-meshing  is broken

### ISSUE THREAD

**Issue by ForrestPi** [mrakotosaon/diff-surface-triangulation#5]
Sorry, I cannot find the link of  https://github.com/mrakotosaon/diff-meshing?  could you update it?

**Comment by mrakotosaon** [comment]
Hi @ForrestPi 
Sorry for the issue, that link is supposed to link to this repo so https://github.com/mrakotosaon/diff-surface-triangulation
Thank you for pointing that out.
Best,
